---

- name: detect | presets
  when:
    - timeweb_server.state | default('present') == 'present'
  block:

    - name: detect | get presets
      ansible.builtin.uri:
        url: '{{ timeweb_account.url }}/presets/servers'
        method: GET
        status_code: 200
        headers:
          Content-Type: application/json
          Authorization: Bearer {{ timeweb_account.api_key }}
      register: timeweb_presets_info
      check_mode: false

    - name: detect | set timeweb_preset_id fact
      ansible.builtin.set_fact:
        timeweb_preset_id: >-
          {{ timeweb_presets_info.json.server_presets |
          selectattr('location', 'equalto', timeweb_account.location) |
          selectattr('cpu', 'equalto', timeweb_server.cpu) |
          sort(attribute='price') |
          map(attribute='id') | first }}

- name: detect | servers
  block:

    - name: detect | get servers
      ansible.builtin.uri:
        url: '{{ timeweb_account.url }}/servers'
        method: GET
        status_code: 200
        headers:
          Content-Type: application/json
          Authorization: Bearer {{ timeweb_account.api_key }}
      register: timeweb_servers_info
      check_mode: false

    - name: detect | set timeweb_server_exists fact
      ansible.builtin.set_fact:
        timeweb_server_exists: false

    - name: detect | set server facts
      ansible.builtin.set_fact:
        timeweb_server_exists: true
        timeweb_server_id: '{{ item.id }}'
      loop: '{{ timeweb_servers_info.json.servers }}'
      loop_control:
        label: '{{ item.name }}'
      when: >-
        ansible_host in (item.networks | default([]) |
        selectattr('type', 'equalto', 'public') |
        map(attribute='ips') | flatten |
        selectattr('type', 'equalto', 'ipv4') |
        map(attribute='ip') | list)

- name: detect | ssh keys
  when:
    - timeweb_server.state | default('present') == 'present'
  block:

    - name: detect | get ssh keys
      ansible.builtin.uri:
        url: '{{ timeweb_account.url }}/ssh-keys'
        method: GET
        status_code: 200
        headers:
          Content-Type: application/json
          Authorization: Bearer {{ timeweb_account.api_key }}
      register: timeweb_ssh_keys_info
      check_mode: false

    - name: detect | set timeweb_ssh_key_exists fact
      ansible.builtin.set_fact:
        timeweb_ssh_key_exists: >-
          {{ true if
          timeweb_ssh_keys_info.json.ssh_keys | selectattr('name', 'equalto', timeweb_server.ssh_key) | length > 0
          else false }}

    - name: detect | set timeweb_ssh_key_id fact
      ansible.builtin.set_fact:
        timeweb_ssh_key_id: >-
          {{ timeweb_ssh_keys_info.json.ssh_keys |
          selectattr('name', 'equalto', timeweb_server.ssh_key) |
          map(attribute='id') | first }}
      when:
        - timeweb_ssh_key_exists

- name: detect | os
  when:
    - timeweb_server.state | default('present') == 'present'
  block:

    - name: detect | get os list
      ansible.builtin.uri:
        url: '{{ timeweb_account.url }}/os/servers'
        method: GET
        status_code: 200
        headers:
          Content-Type: application/json
          Authorization: Bearer {{ timeweb_account.api_key }}
      register: timeweb_os_info
      check_mode: false

    - name: detect | set timeweb_os_id fact
      ansible.builtin.set_fact:
        timeweb_os_id: >-
          {{ timeweb_os_info.json.servers_os |
          selectattr('name', 'equalto', timeweb_server.os_name) |
          selectattr('version', 'equalto', timeweb_server.os_version) |
          map(attribute='id') | first }}
