---

- name: detect
  ansible.builtin.include_tasks:
    file: detect.yml
    apply:
      tags:
        - timeweb.config
        - timeweb.detect
  tags:
    - timeweb.config
    - timeweb.detect

- name: config
  ansible.builtin.include_tasks:
    file: config.yml
    apply:
      tags:
        - timeweb.config
  tags:
    - timeweb.config
