---

- name: config | add ssh keys
  ansible.builtin.uri:
    url: >-
      {{ inferno_account.url + 'sshkey.add' }}
    method: GET
    status_code: 200
    headers:
      Content-Type: application/json
      X-Key: '{{ inferno_account.key }}'
    body:
      cid: '{{ inferno_account.cid | string }}'
      sshkey: >-
        {{ lookup('file',
        lookup('env', 'HOME') + '/.ssh/' +
        inferno_server.ssh_key + '.pub') }}
    body_format: json
  register: inferno_ssh_key_result
  changed_when: "'added' in inferno_ssh_key_result.json.message"

- name: config | reinstall vps
  ansible.builtin.uri:
    url: >-
      {{ inferno_account.url + 'reinstall' +
      '&cid=' + inferno_account.cid | string +
      '&key=' + inferno_account.key +
      '&orderid=' + inferno_order_id +
      '&ostlp=' + inferno_template +
      '&sshkey_ids=' + inferno_ssh_key_id +
      '&run=' + inferno_reinstall | string }}
    method: GET
    status_code: 200
    headers:
      Content-Type: application/json
  register: inferno_reinstall_result
  changed_when: inferno_reinstall_result.json.result == 'success'
  when:
    - inferno_reinstall | bool
  notify:
    - vps | check
