---

- name: detect | get templates list
  ansible.builtin.uri:
    url: >-
      {{ inferno_account.url + 'list' }}
    method: GET
    status_code: 200
    headers:
      Content-Type: application/json
  register: templates_info

- name: detect | set inferno_template fact
  ansible.builtin.set_fact:
    inferno_template: >-
      {{ templates_info.json.ostpls | list |
      select('match', inferno_vps.template) | first }}

- name: detect | get orders info
  ansible.builtin.uri:
    url: >-
      {{ inferno_account.url + 'orders' +
      '&cid=' + inferno_account.cid | string +
      '&key=' + inferno_account.key }}
    method: GET
    status_code: 200
    headers:
      Content-Type: application/json
  register: orders_info

- name: detect | get vps info
  run_once: true
  ansible.builtin.uri:
    url: >-
      {{ inferno_account.url + 'getinfo' +
      '&cid=' + inferno_account.cid | string +
      '&key=' + inferno_account.key + '&orderid=' + item }}
    method: GET
    status_code: 200
    headers:
      Content-Type: application/json
  register: vps_info
  loop: '{{ orders_info.json.orders.keys() }}'

- name: detect | set inferno_vps_order_id fact
  ansible.builtin.set_fact:
    inferno_vps_order_id: >-
      {{ vps_info.results | map(attribute='json') |
      selectattr('vps_info.ip', 'equalto', ansible_host) |
      map(attribute='orderid') | first }}

- name: detect | get ssh keys
  ansible.builtin.uri:
    url: >-
      {{ inferno_account.url + 'sshkey.list' +
      '&cid=' + inferno_account.cid | string +
      '&key=' + inferno_account.key }}
    method: GET
    status_code: 200
    headers:
      Content-Type: application/json
  register: ssh_keys_info

- name: detect | set inferno_ssh_key fact
  ansible.builtin.set_fact:
    inferno_ssh_key_id: >-
      {{ ssh_keys_info.json.list |
      map(attribute="id") | first }}

- name: set inferno_vps_reinstall fact
  ansible.builtin.set_fact:
    inferno_vps_reinstall: '{{ inferno_vps.reinstall | int }}'

- name: inferno | wait for vps
  ansible.builtin.uri:
    url: >-
      {{ inferno_account.url + 'getinfo' +
      '&cid=' + inferno_account.cid | string +
      '&key=' + inferno_account.key +
      '&orderid=' + vps_info.results | map(attribute='json') |
      selectattr('vps_info.ip', 'equalto', ansible_host) |
      map(attribute='orderid') | string }}
    method: GET
    status_code: 200
    headers:
      Content-Type: application/json
  register: vps_info
