---

- name: detect
  ansible.builtin.include_tasks:
    file: detect.yml
    apply:
      tags:
        - inferno.config
        - inferno.detect
  tags:
    - inferno.config
    - inferno.detect

- name: config
  ansible.builtin.include_tasks:
    file: config.yml
    apply:
      tags:
        - inferno.config
  tags:
    - inferno.config

- name: handlers
  ansible.builtin.meta: flush_handlers
