---

galaxy_info:
  role_name: timeweb
  namespace: flyoverhead
  author: flyoverhead
  description: Timeweb Cloud API server configuration
  license: GPL-3.0-only
  min_ansible_version: '2.16'
  galaxy_tags:
    - timeweb

dependencies: []
