---

- name: config | ssh
  when:
    - vdsina_server.state | default('present') == 'present'
    - not vdsina_ssh_key_exists
    - not ansible_check_mode
  block:

    - name: config | create ssh key
      ansible.builtin.uri:
        url: '{{ vdsina_account.url }}/ssh-key'
        method: POST
        status_code: 201
        headers:
          Content-Type: application/json
          Authorization: '{{ vdsina_account.api_key }}'
        body:
          data: >-
            {{ lookup('file',
            lookup('env', 'HOME') + '/.ssh/' +
            vdsina_server.ssh_key + '.pub') }}
          name: '{{ vdsina_server.ssh_key }}'
        body_format: json
      register: vdsina_ssh_key_status
      changed_when: true

    - name: config | set vdsina_ssh_key_id fact
      ansible.builtin.set_fact:
        vdsina_ssh_key_id: >-
          {{ vdsina_ssh_key_status.json.data.id }}

- name: config | server
  block:

    - name: config | create server
      when:
        - not vdsina_server_exists
        - vdsina_server.state | default('present') == 'present'
        - not ansible_check_mode
      block:

        - name: config | create server
          ansible.builtin.uri:
            url: '{{ vdsina_account.url }}/server'
            method: POST
            status_code: 202
            headers:
              Content-Type: application/json
              Authorization: '{{ vdsina_account.api_key }}'
            body:
              datacenter: '{{ vdsina_datacenter_id }}'
              name: '{{ vdsina_server.name }}'
              server-plan: '{{ vdsina_server_plan_id }}'
              ssh-key: '{{ vdsina_ssh_key_id }}'
              template: '{{ vdsina_template_id }}'
            body_format: json
          register: vdsina_server_create_status
          changed_when: true

        - name: config | get created server info
          ansible.builtin.uri:
            url: '{{ vdsina_account.url }}/server/{{ vdsina_server_create_status.json.data.id }}'
            method: GET
            status_code: 200
            headers:
              Content-Type: application/json
              Authorization: '{{ vdsina_account.api_key }}'
          register: vdsina_server_create_info
          until: vdsina_server_create_info.json.data.status == 'active'
          retries: 3
          delay: 90

        - name: config | delete backup schedule
          ansible.builtin.uri:
            url: '{{ vdsina_account.url }}/backup.schedule/{{ vdsina_server_create_info.json.data.id }}'
            method: DELETE
            status_code: 200
            headers:
              Content-Type: application/json
              Authorization: '{{ vdsina_account.api_key }}'
          changed_when: true

        - name: config | set ansible_host fact
          ansible.builtin.set_fact:
            ansible_host: >-
              {{ vdsina_server_create_info.json.data.ip.ip }}

- name: config | save ansible_host fact
  ansible.builtin.lineinfile:
    path: '{{ inventory_dir }}/host_vars/{{ inventory_hostname }}.yml'
    regexp: '^ansible_host:'
    line: 'ansible_host: {{ ansible_host }}'
  when:
    - vdsina_server.state | default('present') == 'present'

- name: config | delete server
  ansible.builtin.uri:
    url: '{{ vdsina_account.url }}/server/{{ vdsina_server_id }}'
    method: DELETE
    status_code:
      - 200
      - 202
    headers:
      Content-Type: application/json
      Authorization: '{{ vdsina_account.api_key }}'
  changed_when: true
  when:
    - vdsina_server_exists
    - vdsina_server.state | default('present') == 'absent'
