---

- name: detect | datacenters
  when:
    - vdsina_server.state | default('present') == 'present'
  block:

    - name: detect | get datacenters
      ansible.builtin.uri:
        url: '{{ vdsina_account.url }}/datacenter'
        method: GET
        status_code: 200
        headers:
          Content-Type: application/json
          Authorization: '{{ vdsina_account.api_key }}'
      register: vdsina_datacenters_info
      check_mode: false

    - name: detect | set vdsina_datacenter_id fact
      ansible.builtin.set_fact:
        vdsina_datacenter_id: >-
          {{ vdsina_datacenters_info.json.data |
          selectattr('country', 'equalto', vdsina_account.country) |
          map(attribute='id') | first }}

- name: detect | servers
  block:

    - name: detect | get servers
      ansible.builtin.uri:
        url: '{{ vdsina_account.url }}/server'
        method: GET
        status_code: 200
        headers:
          Content-Type: application/json
          Authorization: '{{ vdsina_account.api_key }}'
      register: vdsina_servers_info
      check_mode: false

    - name: detect | set vdsina_server_exists fact
      ansible.builtin.set_fact:
        vdsina_server_exists: >-
          {{ true if
          vdsina_servers_info.json.data | selectattr('ip.ip', 'equalto', ansible_host) | length > 0
          else false }}

    - name: detect | set server facts
      ansible.builtin.set_fact:
        vdsina_server_id: >-
          {{ vdsina_servers_info.json.data |
          selectattr('ip.ip', 'equalto', ansible_host) |
          map(attribute='id') | first }}
      when:
        - vdsina_server_exists

- name: detect | server groups
  when:
    - vdsina_server.state | default('present') == 'present'
  block:

    - name: detect | get server groups
      ansible.builtin.uri:
        url: '{{ vdsina_account.url }}/server-group'
        method: GET
        status_code: 200
        headers:
          Content-Type: application/json
          Authorization: '{{ vdsina_account.api_key }}'
      register: vdsina_server_groups_info
      check_mode: false

    - name: detect | set vdsina_server_group_id fact
      ansible.builtin.set_fact:
        vdsina_server_group_id: >-
          {{ vdsina_server_groups_info.json.data |
          selectattr('name', 'equalto', vdsina_server.group) |
          map(attribute='id') | first }}

- name: detect | server plans
  when:
    - vdsina_server.state | default('present') == 'present'
  block:

    - name: detect | get server plans
      ansible.builtin.uri:
        url: '{{ vdsina_account.url }}/server-plan/{{ vdsina_server_group_id }}'
        method: GET
        status_code: 200
        headers:
          Content-Type: application/json
          Authorization: '{{ vdsina_account.api_key }}'
      register: vdsina_server_plans_info
      check_mode: false

    - name: detect | set vdsina_server_plan_id fact
      ansible.builtin.set_fact:
        vdsina_server_plan_id: >-
          {{ vdsina_server_plans_info.json.data |
          selectattr('data.cpu.value', 'equalto', vdsina_server.cpu) |
          map(attribute='id') | first }}

- name: detect | ssh keys
  when:
    - vdsina_server.state | default('present') == 'present'
  block:

    - name: detect | get ssh keys
      ansible.builtin.uri:
        url: '{{ vdsina_account.url }}/ssh-key'
        method: GET
        status_code: 200
        headers:
          Content-Type: application/json
          Authorization: '{{ vdsina_account.api_key }}'
      register: vdsina_ssh_keys_info
      check_mode: false

    - name: detect | set vdsina_ssh_key_exists fact
      ansible.builtin.set_fact:
        vdsina_ssh_key_exists: >-
          {{ true if
          vdsina_ssh_keys_info.json.data | selectattr('name', 'equalto', vdsina_server.ssh_key) | length > 0
          else false }}

    - name: detect | set vdsina_ssh_key_id fact
      ansible.builtin.set_fact:
        vdsina_ssh_key_id: >-
          {{ vdsina_ssh_keys_info.json.data |
          selectattr('name', 'equalto', vdsina_server.ssh_key) |
          map(attribute='id') | first }}
      when:
        - vdsina_ssh_key_exists

- name: detect | templates
  when:
    - vdsina_server.state | default('present') == 'present'
  block:

    - name: detect | templates
      ansible.builtin.uri:
        url: '{{ vdsina_account.url }}/template'
        method: GET
        status_code: 200
        headers:
          Content-Type: application/json
          Authorization: '{{ vdsina_account.api_key }}'
      register: vdsina_templates_info
      check_mode: false

    - name: detect | set vdsina_template_id fact
      ansible.builtin.set_fact:
        vdsina_template_id: >-
          {{ vdsina_templates_info.json.data |
          selectattr('name', 'equalto', vdsina_server.template) |
          map(attribute='id') | first }}
