---

galaxy_info:
  role_name: inferno
  namespace: flyoverhead
  author: flyoverhead
  description: inferno.name API server configuration
  license: GPL-3.0-only
  min_ansible_version: '2.16'
  galaxy_tags:
    - inferno

dependencies: []
